import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./_components/navbar";
import { Toaster } from "sonner";
import Providers from "./_components/providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clips And Pixel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
        <Toaster position="top-center" richColors />
        <html lang="en" className="bg-white text-zinc-700">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
          >
            <Navbar />
            {children}
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
